# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore semver-major updates until Java 17+ is used for builds.
      - dependency-name: "org.hibernate.validator:hibernate-validator"
        update-types: ["version-update:semver-major"]
      # Ignore semver-major updates until Java 17+ is used for builds.
      - dependency-name: "org.mockito:mockito-core"
        update-types: ["version-update:semver-major"]
      # Ignore semver-major updates until Java 17+ is used for builds.
      - dependency-name: "org.junit:junit-bom"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
