language: java
jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

before_script:
  - java -version
  - mvn -v
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      openssl aes-256-cbc -K $encrypted_6e2c8bba47c6_key -iv $encrypted_6e2c8bba47c6_iv -in sec.gpg.enc -out sec.gpg -d ;
      gpg --keyserver keyserver.ubuntu.com --recv-key $SIGNING_KEY ;
      gpg --check-trustdb ;
    fi;

script: ./mvnw clean verify

after_success:
  # push to maven repo
  - if [ $SONATYPE_USERNAME ] && [ -z $TRAVIS_TAG ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      if [ "$TRAVIS_BRANCH" = "master" ]; then
        mvn clean deploy -DskipTests=true -B -U -P release --settings .travis.settings.xml;
        echo "Finished mvn clean deploy for $TRAVIS_BRANCH";
      elif ([[ "$TRAVIS_BRANCH" =~ ^[0-9]+\.[0-9]+\.x$ ]]) ; then
        mvn clean deploy --settings .travis.settings.xml;
        echo "Finished mvn clean deploy for $TRAVIS_BRANCH";
      fi;
    fi;